config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :genres
  root 'movies#index'

  get 'movies/filter/:filter', to: 'movies#index', as: :filtered_movies
  resources :movies do
    resources :reviews
    resources :favorites, only: %i[create destroy]
  end

  resource :session, only: %i[new create destroy]

  resources :users
  get 'signup', to: 'users#new'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6, allow_blank: true }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: %i[new create]
  before_action :require_correct_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @favorite_movies = @user.favorite_movies
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path, notice: 'Thanks for signing up!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Account successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to movies_url, alert: 'Account successfully deleted!'
  end

  private

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local:true) do |f|%>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account", data: { disable_with: false } %>
  <% else %>
    <%= f.submit "Update Account", data: { disable_with: false } %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.count, 'User') %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user_path(user) %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>

</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>

  <div class="actions">
    <% if current_user?(@user) %>
      <%= link_to "Edit Account", edit_user_path(@user), class: "button edit" %>
      <%= link_to 'Delete Account', @user, method: :delete,
              data: { confirm: "Permanently delete your account!?" },
              class: "button delete" %>
    <% end %>
  </div>

  <% if @reviews.present? %>
    <h3>Reviews</h3>
    <% @reviews.each do |review| %>
      <div class="review">
        <div class="details">
          <span class="title">
            <%= link_to review.movie.title, review.movie %>
          </span>
          <%= render "shared/stars", percent: review.stars_as_percent %>
          <span class="date">
            <%= time_ago_in_words(review.created_at) %> ago
          </span>
          <p>
            <%= review.comment %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if @favorite_movies.present? %>
    <h3>Favorite Movies</h3>
    <div class="favorite-movies">
      <% @favorite_movies.each do |movie| %>
        <%= link_to image_tag(movie.image_file_name), movie %>
      <% end %>
    </div>
  <% end %>
</section>